#exclude: '^(\.venv|venv|\.git)/'
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
      -   id: end-of-file-fixer
      -   id: check-toml
      -   id: detect-private-key

  # `flake8` in `pre-commit` has some flaws
  #
  # Ref: https://github.com/pre-commit/pre-commit-hooks/issues/112
  # `pre-commit` won't recognize the `.flake8` file or any config files.
  # This will lead to writing redundant configs in both files, which is not good, IMHO.
  # So, we will comment on this config here - But, either the developer
  # must run the flake8 check his own or must carry out the check during the PR/MR/Push, etc
  #
#  -   repo: https://github.com/PyCQA/flake8
#      rev: 4.0.1
#      hooks:
#      -   id: flake8
#          args: [--config=.flake8]
#          additional_dependencies: [flake8-typing-imports, flake8-bugbear, flake8-print]


  -   repo: meta
      hooks:
      -   id: check-hooks-apply
      -   id: check-useless-excludes

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
